default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"],
      is_key_content_base64: true,
      in_house: false
    )

    match(
      type: "appstore",
      readonly: is_ci,
      api_key: api_key
    )

    increment_build_number(
      build_number: ENV["GITHUB_RUN_NUMBER"] || latest_testflight_build_number(api_key: api_key) + 1,
      xcodeproj: "App.xcodeproj"
    )

    build_app(
      workspace: nil,
      project: "App.xcodeproj",
      scheme: "App",
      export_method: "app-store",
      clean: true,
      output_directory: "./build",
      output_name: "Roof.ipa"
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end

  desc "Push a new release build to the App Store"
  lane :release do
    setup_ci

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"],
      is_key_content_base64: true,
      in_house: false
    )

    match(
      type: "appstore",
      readonly: is_ci,
      api_key: api_key
    )

    increment_build_number(
      build_number: ENV["GITHUB_RUN_NUMBER"] || latest_testflight_build_number(api_key: api_key) + 1,
      xcodeproj: "App.xcodeproj"
    )

    build_app(
      workspace: nil,
      project: "App.xcodeproj",
      scheme: "App",
      export_method: "app-store",
      clean: true,
      output_directory: "./build",
      output_name: "Roof.ipa"
    )

    upload_to_app_store(
      api_key: api_key,
      skip_screenshots: true,
      skip_metadata: true,
      submit_for_review: false,
      automatic_release: false
    )
  end
end
